### ISSUE TITLE
General Machine drawings / reference dimensions

### ISSUE THREAD

**Issue by goscommons** [goscommons/Grapples#12]
Is good to have a first overview of the machine by giving front side and maybe isometric view with some key dimensions, to get an idea of size.
![image](https://user-images.githubusercontent.com/34537534/39876200-dce2acba-5472-11e8-8993-1354c82913a3.png)
![image](https://user-images.githubusercontent.com/34537534/39876288-10073994-5473-11e8-8333-27177d97b172.png)

**Comment by polemidis** [comment]
Important measurements are the distance between tines, overall width (C), what is the opening of the "mouth". Length of the tines (kind of the "B" but not exactly as the grapple sits on the front part of the tines) so the consumer knows how much material it can grab.

**Comment by jurra** [comment]
I think an indication in a rough sketch, with the dimensions @polemidis mentions can help @cls-c.

**Comment by krishnarajagopal2011** [comment]
Hey I am making the 2D drawing of the Grapples, I am using solidworks as of now though.
